package com.dcmc.apps.taskmanager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaskStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskStatusAllPropertiesEquals(TaskStatus expected, TaskStatus actual) {
        assertTaskStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertTaskStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskStatusAllUpdatablePropertiesEquals(TaskStatus expected, TaskStatus actual) {
        assertTaskStatusUpdatableFieldsEquals(expected, actual);
        assertTaskStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskStatusAutoGeneratedPropertiesEquals(TaskStatus expected, TaskStatus actual) {
        assertThat(actual)
            .as("Verify TaskStatus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskStatusUpdatableFieldsEquals(TaskStatus expected, TaskStatus actual) {
        assertThat(actual)
            .as("Verify TaskStatus relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getVisible()).as("check visible").isEqualTo(expected.getVisible()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskStatusUpdatableRelationshipsEquals(TaskStatus expected, TaskStatus actual) {
        // empty method
    }
}
